
export const ICONS = {
  settings: 'settings-outline',
  back: 'arrow-back-outline',
  Clipboard:'clipboard-outline',
  close: 'close-outline',
  chevronDown: 'chevron-down-outline',
  chevronUp: 'chevron-up-outline',
  chevronForward: 'chevron-forward-outline',
  play: 'play-outline',
  pause: 'pause-outline',
  flashlight: 'flashlight-outline',
  power: 'power-outline',
  phonePortrait: 'phone-portrait-outline',
  notifications: 'notifications-outline',
  compass: 'compass-outline',
  volumeHigh: 'volume-high-outline',
  handLeft: 'hand-left-outline',
  batteryWarning: 'battery-dead-outline',
  timer: 'timer-outline',
  language: 'language-outline',
  star: 'star-outline',
  share: 'share-outline',
  shieldCheckmark: 'shield-checkmark-outline',
} as const;